use_frameworks!

platform :ios, '9.0'

target 'JKSwiftNetProcessor_Example' do
  pod 'JKSwiftNetProcessor', :path => '../'
  pod 'JKSwiftExtension'
  pod 'SnapKit', '4.2.0'
  target 'JKSwiftNetProcessor_Tests' do
    inherit! :search_paths

  end
end
